=== matrizaev/sap2ism/scheme.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="document_list">
		<xs:complexType>
			<xs:sequence maxOccurs="unbounded">
				<xs:element name="document">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="type">
								<xs:simpleType>
									<xs:restriction base="xs:integer">
										<xs:minInclusive value="0"/>
										<xs:maxInclusive value="104"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="number" type="nonemptystringType50"/>
							<xs:element name="author" type="nonemptystringType50"/>
							<xs:element name="department" minOccurs="0" maxOccurs="1">
								<xs:simpleType>
									<xs:restriction base="xs:integer">
										<xs:minInclusive value="0"/>
										<xs:maxInclusive value="104"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="date" type="xs:date"/>
							<xs:element name="description" type="canemptystringType512"/>
							<xs:element name="validity" minOccurs="0">
								<xs:complexType>
									<xs:choice maxOccurs="unbounded">
										<xs:element name="change" type="idType" />
										<xs:element name="cancel" type="idType" />
									</xs:choice>
								</xs:complexType>
							</xs:element>
							<xs:element name="file_list">
								<xs:complexType>
									<xs:sequence maxOccurs="unbounded">
										<xs:element name="file">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="file_description" type="nonemptystringType50" />
													<xs:element name="file_name" type="filenameType" />
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>	
							</xs:element>
						</xs:sequence>
						<xs:attribute name="id" type="idType"/>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
		<xs:unique name="unique-document-id">
			<xs:selector xpath="document"/>
			<xs:field xpath="@id"/>
		</xs:unique>
	</xs:element>
	<xs:simpleType name="idType">
		<xs:restriction base="xs:integer">
			<xs:pattern value="7[0-9]00[0-9]{14}" />
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="filenameType">
		<xs:restriction base="xs:string">
			<xs:pattern value="\s*7[0-9]00[0-9]{16}(\.[a-zA-Z0-9]{0,4})?\s*" />
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="nonemptystringType50">
		<xs:restriction base="xs:string">
			<xs:minLength value="1"/>
			<xs:pattern value="\s*\S+.*\s*" />
			<xs:maxLength value="50"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="canemptystringType512">
		<xs:restriction base="xs:string">
			<xs:maxLength value="512"/>
		</xs:restriction>
	</xs:simpleType>	
</xs:schema>

=== matrizaev/sap2ism/load/PR15091701.xml
<?xml version="1.0" encoding='UTF-8'?>
<document_list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="scheme.xsd">
	<document id="700012345678912345">
		<type>1</type>
		<number>34-06/234234.01</number>
		<author>Иванов И. И.</author>
		<date>2012-12-13</date>
		<description>
			abcde
		</description>
		<validity>
			<change>
				700012345678912346
			</change>
			<cancel>
				700012345678912349
			</cancel>
		</validity>
		<file_list>
			<file>
				<file_description>
					Приложение
				</file_description>
				<file_name>
					70001234567891234501
				</file_name>
			</file>
			<file>
				<file_description>
					Приложение
				</file_description>
				<file_name>
					70001234567891234502.xml
				</file_name>
			</file>
		</file_list>
	</document>
</document_list>
